language: python
python:
  - 2.7
  - 3.5
  - 3.6

env:
  - DJANGO="django<1.12"
  - DJANGO="django<2.1"
  - DJANGO="django<2.2"

install:
  - pip install -q $DJANGO
  - python setup.py -q install

script:
  - ./manage.py test --settings=admin_sort.tests.settings
